---
- hosts: all
  become: yes
  tasks:
    - name: ensure apt cache is the latest
      apt: update_cache=yes upgrade=yes cache_valid_time=86400

- hosts: web
  become: yes
  roles:
    - apache

- hosts: db
  become: yes
  roles:
    - postgresql
    - memcache

- hosts: web
  roles:
    - drupal7
